//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnketniSustavZaKucanstvoLibrary.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kucanstvo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kucanstvo()
        {
            this.Anketas = new HashSet<Anketa>();
        }
    
        public int IDKucanstvo { get; set; }
        public string Sifra { get; set; }
        public int VlasnikKucanstvaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anketa> Anketas { get; set; }
        public virtual VlasnikKucanstva VlasnikKucanstva { get; set; }
    }
}
